module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: {
    standard: [
      "open",
      "active",
      "bio",
      "eyebrow",
      "meta-strip",
      "inline-logo",
      "section-rule",
      "home-section",
      "profile__card",
      "mono-meta",
      "footer__ornament",
      "author-self",
      "selected-dot",
      "venue-pill",
      "stat-pill",
      "stat-pill-row",
      "stat-pill__label",
      "stat-pill__value",
      "badge-pill",
      "badge-pill__label",
      "badge-pill__value",
      "news-list",
      "news-row",
      "news-date",
      "news-body",
      "news-title",
      "news-year",
      "news-archive",
      "cv-section",
      "cv-section__title",
      "cv-timeline",
      "cv-year",
      "cv-entry",
      "cv-pdf-button",
      "btn-outline-red",
      "filter-chips",
      "project-tags",
      "project-meta",
      "search-pill",
      "expand-panel",
      "about-header",
      "about-title",
      "about-subtitle",
    ],
    deep: [/^cv-/, /^news-/, /^stat-pill/, /^badge-pill/, /^project-/, /^ti-/, /^ai-/, /^fa-/],
    greedy: [/^tabler/, /^font-awesome/],
  },
};
