module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: {
    standard: [
      "open",
      "active",
      "bio",
      "eyebrow",
      "meta-strip",
      "inline-logo",
      "home-section",
      "profile__card",
      "mono-meta",
      "footer__ornament",
      "author-self",
      "selected-dot",
      "venue",
      "badge-pill",
      "badge-pill__label",
      "badge-pill__value",
      "news-list",
      "news-row",
      "news-date",
      "news-body",
      "news-title",
      "news-year",
      "news-archive",
      "cv-section",
      "cv-section__title",
      "cv-timeline",
      "cv-year",
      "cv-entry",
      "cv-pdf-button",
      "btn-outline-accent",
      "cv-year-badge",
      "filter-chips",
      "project-tags",
      "project-meta",
      "expand-panel",
      "about-header",
      "about-title",
      "about-subtitle",
      "home-list",
      "home-list__sub",
      "about-me",
      "memories-list",
      "memory-date",
      "photo-row",
      "photo-caption",
      "about-hero",
      "about-hero__text",
      "about-hero__media",
      "research-block",
      "research-block__figure",
      "research-block__group",
      "home-more",
      "pub-links",
      "pub-stats",
      "reveal-pending",
      "reveal-visible",
    ],
    deep: [/^cv-/, /^news-/, /^badge-pill/, /^project-/, /^about-hero/, /^research-block/, /^ti-/, /^ai-/, /^fa-/],
    greedy: [/^tabler/, /^font-awesome/, /:focus-visible/],
  },
};
